name: video-evaluation
channels:
  - pytorch
  - conda-forge

dependencies:
  # Python version (compatible with current environment)
  - python=3.10
  
  # Core dependencies (minimal versions to avoid conflicts)
  - numpy
  - scipy
  - pillow
  - tqdm
  - pyyaml
  
  # Computer vision basics
  - scikit-image
  - ffmpeg
  
  # Audio processing
  - librosa
  
  # Performance optimization
  - numba
  
  # Pip dependencies
  - pip
  - pip:
    # Audio feature extraction
    - python_speech_features>=0.6.0
    
    # Video processing tools
    - ffmpeg-python>=0.2.0
    - scenedetect>=0.6.0
    
    # Image quality metrics
    - lpips>=0.1.4
    
    # CLIP for similarity calculation
    - git+https://github.com/openai/CLIP.git
    
    # High-priority packages (installed separately via setup.py)
    # - ultralytics  # YOLOv8 face detection
    # - vbench       # Video evaluation benchmark
    # - mediapipe    # Advanced face detection (Python 3.8-3.12 only)
    
    # Basic OpenCV (conda version may conflict)
    - opencv-python-headless>=4.5.0

# Installation Notes:
# 1. If you already have a VBench conda environment, use that instead:
#    conda activate vbench
#    pip install lpips python_speech_features scenedetect mediapipe git+https://github.com/openai/CLIP.git
#
# 2. This environment provides all dependencies for:
#    - LSE calculation and basic metrics
#    - CLIP similarity calculation
#    - FVD calculation (using torchvision)
#    - GIM matching (custom implementation)
#    For VBench integration, ensure VBench is available in your environment
#
# 3. Advanced face detection: MediaPipe is included by default for better performance
#    You can also install ultralytics for YOLOv8-based face detection
#
# 4. GPU support: Ensure CUDA-compatible PyTorch is installed for better performance
#
# 5. New advanced metrics:
#    - CLIP-V: Calculate CLIP similarity between source and target frames
#    - FVD-V: Fréchet Video Distance for video quality assessment
#    - GIM: Graph Image Matching for synchronization evaluation (requires separate install)
#
# 6. Official GIM integration (recommended for best accuracy):
#    After creating the environment, install GIM:
#    conda activate video-evaluation
#    git clone https://github.com/xuelunshen/gim.git
#    cd gim && pip install -e . && cd .. 